// <auto-generated />
namespace SchoolManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedcalendarfieldsstartdateandenddatefromdatetimetodateonly : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedcalendarfieldsstartdateandenddatefromdatetimetodateonly));
        
        string IMigrationMetadata.Id
        {
            get { return "201708251027405_changed calendar fields startdate and enddate from datetime to date only"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
