// <auto-generated />
namespace SchoolManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removedchangestocalendarieaddedcalculatedcolumnyear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removedchangestocalendarieaddedcalculatedcolumnyear));
        
        string IMigrationMetadata.Id
        {
            get { return "201708281246508_Removed changes to calendar i.e added calculated column year"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
